# Generated by Django 6.1 on 2026-09-13 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('elementary', 'Sekolah Dasar'), ('junior-high', 'Sekolah Menengah Pertama'), ('senior-high', 'Sekolah Menengah Atas'), ('bachelor', 'Sarjana'), ('master', 'Magister'), ('doctoral', 'Doktor'), ('course', 'Kursus & Sertifikasi')], default='bachelor', max_length=20)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_year', 'institution'],
            },
        ),
    ]
