# Generated by Django 6.1 on 2026-09-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_url',
            field=models.URLField(blank=True),
        ),
    ]
